"""Emit build metadata for frozen builds and Windows EXE version resources.

Run from the repository root (the packaging script does this before PyInstaller):

    python packaging/write_build_info.py

Writes:

- ``src/_version_build.py`` — imported at runtime in packaged and dev installs
  when present.
- ``packaging/windows_file_version_info.txt`` — passed to PyInstaller ``EXE(version=...)``.
"""

from __future__ import annotations

import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python <3.11 fallback
    tomllib = None  # type: ignore[assignment]


ROOT = Path(__file__).resolve().parents[1]
BUILD_PY = ROOT / "src" / "_version_build.py"
VERSION_INFO_TXT = ROOT / "packaging" / "windows_file_version_info.txt"


def _read_pyproject_version() -> str:
    path = ROOT / "pyproject.toml"
    text = path.read_text(encoding="utf-8")
    if tomllib is not None:
        try:
            data = tomllib.loads(text)
            return str(data.get("project", {}).get("version", "0.0.0"))
        except Exception:
            pass
    match = re.search(r'(?m)^version\s*=\s*"([^"]+)"', text)
    return match.group(1) if match else "0.0.0"


def _run_git(args: list[str]) -> tuple[int, str]:
    try:
        proc = subprocess.run(
            ["git", "-C", str(ROOT), *args],
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
        return proc.returncode, (proc.stdout or "").strip()
    except (OSError, subprocess.TimeoutExpired):
        return 1, ""


_SEMVER_DESCRIBE = re.compile(
    r"^v?(?P<maj>\d+)\.(?P<min>\d+)\.(?P<pat>\d+)"
    r"(?:-(?P<commits>\d+)-g[0-9a-f]+)?(?:-dirty)?$",
    re.IGNORECASE,
)


def _parse_file_version(
    describe: str, fallback_semver: str
) -> tuple[int, int, int, int]:
    match = _SEMVER_DESCRIBE.match(describe.strip())
    if match:
        maj = int(match.group("maj"))
        mn = int(match.group("min"))
        pat = int(match.group("pat"))
        commits = int(match.group("commits") or "0")
        return maj, mn, pat, commits
    parts = fallback_semver.replace("v", "").split(".")
    try:
        nums = [int(re.sub(r"[^0-9].*", "", p)) for p in (parts + ["0", "0", "0"])[:3]]
        return nums[0], nums[1], nums[2], 0
    except ValueError:
        return 0, 1, 0, 0


def _windows_version_info_text(
    *,
    file_version: tuple[int, int, int, int],
    product_version_str: str,
    git_commit: str,
) -> str:
    fv = file_version
    fvs = f"{fv[0]}.{fv[1]}.{fv[2]}.{fv[3]}"
    legal = "Licensed under GPL-3.0"
    commit_note = git_commit[:12] if git_commit else "unknown"
    return f"""# UTF-8
#
# Generated by packaging/write_build_info.py for PyInstaller.
#
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={fv},
    prodvers={fv},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
    ),
  kids=[
    StringFileInfo(
      [
      StringTable(
        u'040904B0',
        [
        StringStruct(u'CompanyName', u'Michael Hedges'),
        StringStruct(u'FileDescription', u'Audio Analyser'),
        StringStruct(u'FileVersion', u'{fvs}'),
        StringStruct(u'InternalName', u'AudioAnalyser'),
        StringStruct(u'LegalCopyright', u'{legal}'),
        StringStruct(u'OriginalFilename', u'AudioAnalyser.exe'),
        StringStruct(u'ProductName', u'Audio Analyser'),
        StringStruct(u'ProductVersion', u'{product_version_str}'),
        StringStruct(u'Comments', u'Git {commit_note}')
        ])
      ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""


def main() -> int:
    py_project_version = _read_pyproject_version()
    rc, commit_full = _run_git(["rev-parse", "HEAD"])
    if rc != 0:
        commit_full = ""
    rc_d, describe = _run_git(["describe", "--always", "--tags", "--dirty"])
    if rc_d != 0 or not describe:
        describe = commit_full[:12] if commit_full else py_project_version

    dirty = describe.endswith("-dirty")
    version_pep = describe.removesuffix("-dirty") if dirty else describe
    tag_match = re.match(r"^v?(?P<semver>\d+\.\d+\.\d+)", version_pep.strip())
    if tag_match:
        release_version = tag_match.group("semver")
    else:
        release_version = py_project_version

    file_ver = _parse_file_version(
        version_pep if version_pep else describe, py_project_version
    )
    build_date = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    BUILD_PY.parent.mkdir(parents=True, exist_ok=True)
    BUILD_PY.write_text(
        '''"""Auto-generated by packaging/write_build_info.py — do not edit."""\n'''
        f"VERSION = {release_version!r}\n"
        f"GIT_COMMIT_FULL = {commit_full!r}\n"
        f"GIT_DESCRIBE = {describe!r}\n"
        f"BUILD_DATE_UTC = {build_date!r}\n"
        f"WORKING_TREE_DIRTY = {dirty!r}\n"
        f"FILE_VERSION_TUPLE = {file_ver!r}\n",
        encoding="utf-8",
    )

    VERSION_INFO_TXT.parent.mkdir(parents=True, exist_ok=True)
    VERSION_INFO_TXT.write_text(
        _windows_version_info_text(
            file_version=file_ver,
            product_version_str=(
                (describe if describe else release_version).replace('"', "'")[:90]
            ),
            git_commit=commit_full,
        ),
        encoding="utf-8",
    )
    print(f"Wrote {BUILD_PY.relative_to(ROOT)}")
    print(f"Wrote {VERSION_INFO_TXT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
